### ISSUE TITLE
versions of dependecies

### ISSUE THREAD

**Issue by wuusn** [DIAGNijmegen/pathology-hooknet#1]
hi, I am trying to explore your hooknet, but get some problems from the start.
The **Readme** says "keras==2.0.8 and tensorflow-gpu==1.14", however, the **requirements.txt** says "tensorflow_gpu==2.3.1", did you mean your code work both in these different versions?
However, I still got errors after trying both of them.

-  when I use the versions of **Readme**, I got this error:

```
Traceback (most recent call last):
  File "train.py", line 5, in <module>
    from source.model import HookNet
  File "/dir/pathology-hooknet/hooknet/source/model.py", line 23, in <module>
    from tensorflow.keras.layers.experimental.preprocessing import Rescaling
ModuleNotFoundError: No module named 'tensorflow.keras.layers.experimental.preprocessing'
```

- When I use the versions of **readme**, I got this error:
```
Traceback (most recent call last):
  File "train.py", line 65, in <module>
    train()
  File "train.py", line 58, in train
    output_path=config['output_path'])
  File "/dir/pathology-hooknet/hooknet/source/trainer.py", line 140, in __init__
    self._graph = tf.get_default_graph()
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'
```
I am not familiar with tensorflow yet, any suggestions?

**Comment by martvanrijthoven** [comment]
Hi Yuxin Wu,

Thanks for exploring HookNet :). I am sorry the code is not working for you. The problem was that I updated the model to TensorFlow 2.3.0. However, the training script in this repository is just for the sake of an example. I forgot to update this script. Sorry about this. I have now also updated the training script (and the readme). Please let me know if you still have problems, and I will fix them asap.

**Comment by wuusn** [comment]
hi martvanrijthoven,
Thanks for your quick response.  It works! However, maybe you forget to re-add the `argconfigparser.py ` file to the dir of `hooknet`. I tried to make a pull request to add this file for you. #2

**Comment by martvanrijthoven** [comment]
Hi Yuxin Wu,

Great to hear that it works! I renamed the argconfigparser/argconfigparser.py to  argconfigparser/\_\_init\_\_.py and indeed forgot to push it. Thanks for the help!
