### ISSUE TITLE
TypeError: create_batch_iterator() got an unexpected keyword argument 'batches'

### ISSUE THREAD

**Issue by Noemie-B** [DIAGNijmegen/pathology-hooknet#13]
Hi
I want to launch the same script you gave in example (HookNetPracticalGuide) but I'm facing the following issue when I'm trying to execute the function : 

with create_batch_iterator(mode=mode, 
                           user_config=user_config, batches=batches, 
                           cpus=4) as training_iterator:
    
    for x_batch, y_batch in training_iterator:
        print('batch shapes:')
        print(f'x_shape: {x_batch.shape}')
        print(f'y_shape: {y_batch.shape}')
        plot_sample(x_batch[0], y_batch[0])
....

which is  : TypeError: create_batch_iterator() got an unexpected keyword argument 'batches'

Do you know what happened here ?

Thanks for your help !

**Comment by martvanrijthoven** [comment]
Dear Noemie-B,

Thank you for your interest in HookNet!

The Jupyter notebook HookNetPracticalGuide became incompatible with the new version of wholeslidedata. Sorry for the inconvenience. I have now updated the notebook, and everything should work again.

Please let me know if you still have issues or any other questions.

Best wishes,
Mart

**Comment by Noemie-B** [comment]
Waouw, thank you for your very quick answer ! 

It works now. Thanks again and have a great day
