### ISSUE TITLE
cannot import name 'WholeSlideMaskWriter' from 'wholeslidedata.image'

### ISSUE THREAD

**Issue by elif011** [DIAGNijmegen/pathology-hooknet#14]
Hello, 

I wanted to try the example inference ipynb code but I get the error in the following: ImportError: cannot import name 'WholeSlideMaskWriter' from 'wholeslidedata.image'. I installed the wholeslidedata but I still get this error. Could you please help me about this issue?

**Comment by martvanrijthoven** [comment]
Hi Elif011,

Thank you for your interest in HookNet!

For the inference code, [ASAP](https://github.com/computationalpathologygroup/ASAP/releases/tag/ASAP-2.1) needs to be installed (to write the output tif file). Could you please verify if you have ASAP installed correctly?

**Comment by elif011** [comment]
Hi, 

Yes I installed the ASAP by running ASAP-2.1-py38-win64.exe and still I am getting the same error

**Comment by martvanrijthoven** [comment]
Hi Elif011,

Ok great. Could you please check if you can import multiresolutionimageinterface?

`import multiresolutionimageinterface`


Best wishes,
Mart

**Comment by elif011** [comment]
Hi Mart, 

I installed the ASAP via exe , put the bin path of it to the system path but I cannot import the multiresolutionimageinterface and WholeSlideMaskWriter. 

Also thank you for your fast replies.

**Comment by elif011** [comment]
I also have a big question about the HookNetPracticalGuide.ipynb. Basically I want to test your model to find tumor buddings in my mrxs image. For this purpose, I want to use your inference codes, but in your inference.ipynb I get the import error and in HookNetPracticalGuide.ipynb I only get the full tumor classification for the patches. I watched your video tutorials and examined your codes and changed the class number to 1 so that I can only do binary classification on the patches and I also changed the context and target patch spacing to 0.25 to 1.0 for my image. I want to ask that what I should do to see binary segmentation on my image in training ? In my training, training loss is decreasing after 200 repeats with 20 batch but inference results only show full tumor segmentation. 

I really appreaciate your help for this issue. 
Best regards,

**Comment by martvanrijthoven** [comment]
Hi Elif011,

Ok it seems that python cannot find the multiresolutionimageinterface (and therefore the import of the WholeSlideMaskWriter fails). I don't have a windows machine myself, so i am not 100% what is going wrong. Maybe you can try to add the bin folder also to PYTHONPATH?
Which python, ASAP, windows versions are you using?

**Comment by elif011** [comment]
Hi Mart, 

I am using Python 3.8.13, ASAP2.1 win64 windows 10.

**Comment by martvanrijthoven** [comment]
> I also have a big question about the HookNetPracticalGuide.ipynb. Basically I want to test your model to find tumor buddings in my mrxs image. For this purpose, I want to use your inference codes, but in your inference.ipynb I get the import error and in HookNetPracticalGuide.ipynb I only get the full tumor classification for the patches. I watched your video tutorials and examined your codes and changed the class number to 1 so that I can only do binary classification on the patches and I also changed the context and target patch spacing to 0.25 to 1.0 for my image. I want to ask that what I should do to see binary segmentation on my image in training ? In my training, training loss is decreasing after 200 repeats with 20 batch but inference results only show full tumor segmentation.
> 
> I really appreaciate your help for this issue. Best regards,

Ok your application sounds very cool.  HookNet is a segmentation model, so you cannot do patch classification with it. If you want to use binary segmentation, you will only need to change the label_map. For example, change it to 
```yaml
label_map:
   tumor: 1
```
If you want me to check your config files, I would be happy to have a look at those

Best wishes,
Mart

**Comment by elif011** [comment]
I really appreciate your help and I can send my codes with the changes I made for the tumor budding segmentation. I would be very happy to get your help and see the results. I will send my config files to your email and wait for your reply. 

Best regards,

**Comment by martvanrijthoven** [comment]
> Hi Mart,
> 
> I am using Python 3.8.13, ASAP2.1 win64 windows 10.

Ok, this sounds all good. I suggest you check the open/closed issues on https://github.com/computationalpathologygroup/ASAP/issues
and open a new issue in the ASAP repository if you cannot solve it. I am sorry I can not help you further with the ASAP intstallation.

**Comment by elif011** [comment]
Okay, thank you so much for your help.
