### ISSUE TITLE
Lung annotations

### ISSUE THREAD

**Issue by usuyama** [DIAGNijmegen/pathology-hooknet#16]
Hi @martvanrijthoven 

Is the lung dataset publicly available?

**Comment by usuyama** [comment]
I noticed the closed issue on the breast dataset #6

**Comment by martvanrijthoven** [comment]
Dear Naoto Usuyama,

I'm sorry for this very late response. I completely missed this. Unfortunately, I can also not share the lung annotations.

Best wishes,
Mart
