### ISSUE TITLE
The link to the data is no longer valid.

### ISSUE THREAD

**Issue by tizikaoroubanfan** [DIAGNijmegen/pathology-hooknet#24]
Dear author, hello! Thank you very much for your work, I have learned a lot! I tried to reproduce the HookNet-torch - practical guide you provided, but I encountered a problem when downloading TCGA-21-5784-01Z-00-DX1.tif. The link https://drive.google.com/uc?id=1NefnQu3e0l4WR7Xb809gpVORXrKpJb0q is no longer valid. I hope you can update it with a new link. Thank you very much! Looking forward to your reply!

**Comment by martvanrijthoven** [comment]
Dear tizikaoroubanfan,

Thanks for pointing out this issue. I have updated the link! 

Bes wishes,
Mart

**Comment by pstew** [comment]
Hello, I am not able to access the Google Drive link above. Could you please provide an updated link or let us know another way to grab the tif? Thank you!

**Comment by martvanrijthoven** [comment]
Dear Paul Stewart,

The links are updated in code, so the notebook should work. But you can manually download with gdown:
gdown "https://drive.google.com/uc?id=1a-77TNRlSoPbRlNI0VtlHG3d7xTSpcwB" -O /tmp/TCGA-21-5784-01Z-00-DX1.tif

or you can download from here: 
https://drive.google.com/file/d/1a-77TNRlSoPbRlNI0VtlHG3d7xTSpcwB/view?usp=drive_link

If you still have problems obtaining the file please let me know.

Best wishes,
Mart

**Comment by pstew** [comment]
Awesome, thank you for the quick response. File is downloading as I type. I greatly appreciate it.
