### ISSUE TITLE
Structure of 'data' file

### ISSUE THREAD

**Issue by AyaAq** [DIAGNijmegen/pathology-hooknet#5]
I am trying to run the training for the model with all the default values, but I am getting this error: ValueError: Input 0 of layer conv2d is incompatible with the layer: : expected min_ndim=4, found ndim=2. Full shape received: [None, 284]. I am suspecting the problem might be that the batchgenerator is not reading in the files properly. What is the file structure the model training script assumes? 

Thanks,
Aya

**Comment by martvanrijthoven** [comment]
Hi Aya,

Sorry for the inconvenience. I have fixed this error now and train.py should work again. You should now set both the input_shape for the target and the context branch as a list of list (please see the change in the train_parameters.yml file)

**Comment by martvanrijthoven** [comment]
Extra Note:
The batch generator does not read any files, it generates random values, just for illustration purposes. You have to create your own batch generator, for now. I hope I can publically release the batch generator that I have used in the paper, soon.
