### ISSUE TITLE
ImageReader: self.__image.close() does not exist in ASAP.

### ISSUE THREAD

**Issue by robogast** [DIAGNijmegen/pathology-hooknet#8]
When using the latest version of ASAP (https://github.com/computationalpathologygroup/ASAP/commit/8c9a8fbf32fd7a9dc5c5ec4d5c3552923cc4890a), the [ImageReader](https://github.com/DIAGNijmegen/pathology-hooknet/blob/master/hooknet/source/image/imagereader.py)'s `ImageReader.__del__` function repeatedly gets called, which then calls `ImageReader.close()`, which tries to execute the following:
```python
def close(self):
    """Close the image object. No further reading is possible after calling this function."""

    if self.__image is not None:
        self.__image.close()
        self.__image = None
```
However, ASAP's `MultiResolutionImage` only has an `open` function, but no `close`, resulting in the following exception:
```python
Exception ignored in: <function ImageReader.__del__ at 0x1533e9a82a60>
Traceback (most recent call last):
  File "/home/robertsc/2D-VQ-AE-2/wsi_io/imagereader.py", line 59, in __del__
    self.close()
  File "/home/robertsc/2D-VQ-AE-2/wsi_io/imagereader.py", line 556, in close
    self.__image.close()
AttributeError: 'MultiResolutionImage' object has no attribute 'close'
```
Is this an issue on ASAP's end, or on yours?

**Comment by martvanrijthoven** [comment]
Hi Robogast,

Thanks for your issue.

This is due to ASAP changed the interface, i.e, it removed the close method. Please see https://github.com/computationalpathologygroup/ASAP/issues/203 for more information. 

I will try to fix this beginning of next week and make the code compatible with both the old and new ASAP versions.

**Comment by martvanrijthoven** [comment]
Fixed (please use wholeslidedata (https://github.com/DIAGNijmegen/pathology-whole-slide-data/tree/main/wholeslidedata)
