### ISSUE TITLE
ModuleNotFoundError: No module named 'multiprocessing.shared_memory'

### ISSUE THREAD

**Issue by gotjd709** [DIAGNijmegen/pathology-hooknet#9]
I git clone this repository and **build docker images** and run jupyter notebook with 'HookNetPractice.ipynb'. 

When I run `from wholeslidedata.iterators import create_batch_iterator`

I met the error message like 
> ModuleNotFoundError: No module named 'multiprocessing.shared_memory'

I found that python 3.8 has **class multiprocessing.shared_memory.SharedMemory()** but python 3.6 doesn't.

However, In this repository, Dockerfile has python 3.6.

How can I solve this?

**Comment by martvanrijthoven** [comment]
Thanks for the issue!

Indeed wholeslidedata package requires python>=3.8, i will update the Dockerfile

**Comment by martvanrijthoven** [comment]
Hi Gotjd709,

I updated the docker, it now includes everything to run the notebook. I hope HookNet will be useful to you!

Kind regards, 
Mart

**Comment by gotjd709** [comment]
Thank you!
